
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;/*/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class BirthSearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form BirthSearch
     */
    DefaultTableModel model;
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public BirthSearch() {
        initComponents();
        model=(DefaultTableModel) jTable_Users.getModel();
        findUsers();
    }
public Connection getConnection()
    {
     
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return con;
    }
    
 // function to return users arraylist with particular data 
    public ArrayList<BirthClass> ListUsers(String ValToSearch)
    {
        ArrayList<BirthClass> usersList = new ArrayList<BirthClass>();
        
        Statement st;
        ResultSet rs;
        
        try{
          con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `birthtable` WHERE CONCAT(firstname,lastname,dob,timeofbirth,placeofbirth,city,taluka,district,gender,regno,regdate,mothername,fathername) LIKE '%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            BirthClass birthclass;
            //BirthClass b;
            
            while(rs.next())
            {
               birthclass = new BirthClass(
                                 
                                 rs.getString("firstname"),
                                 rs.getString("lastname"),
                                 rs.getDate("dob"),
                                 rs.getTime("timeofbirth"),
                                 rs.getString("placeofbirth"),
                                 rs.getString("city"),
                                 rs.getString("taluka"),
                                 rs.getString("district"),
                                 rs.getString("gender"),
                                 rs.getInt("regno"),
                                 rs.getDate("regdate"),
                                 rs.getString("mothername"),
                                 rs.getString("fathername")
               
                                );
               usersList.add(birthclass);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    
    // function to display data in jtable
    public void findUsers()
    {
        ArrayList<BirthClass> users = ListUsers(jText_search.getText());
     
        model.setColumnIdentifiers(new Object[]{"Fname","Lname","DOB","Birth_time","Birth_place","City"," Taluka","District","Gender","Regno"," RegDate","Mother_name","Father_name"});
        Object[] row = new Object[13];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getFname();
            row[1] = users.get(i).getLname();
            row[2] = users.get(i).getDOB();
            row[3] = users.get(i).getBirth_time();
            row[4] = users.get(i).getBrith_place();
            row[5] = users.get(i).getCity();
            row[6] = users.get(i).getTaluka();
            row[7] = users.get(i).getDistrict();
            row[8] = users.get(i).getGender();
            row[9] = users.get(i).getRegno();
            row[10] = users.get(i).getRegDate();
            row[11] = users.get(i).getMother_name();
            row[12] = users.get(i).getFather_name();
        model.addRow(row);
            
        }
       jTable_Users.setModel(model);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jText_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, 30));
        getContentPane().add(jText_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 200, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 90, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 67, -1));

        jTable_Users.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fname", "Lname", "DOB", "Birth_time", "Birth_place", "City", "Taluka", "District", "Gender", "Regno", "RegDate", "Mother_name", "Father_name"
            }
        ));
        jTable_Users.setPreferredSize(new java.awt.Dimension(975, 600));
        jTable_Users.setRowHeight(22);
        jTable_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Users);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 1080, 99));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Fname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Lname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("DOB");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Birth_time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Birth_place");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("City");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Taluka");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("District");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Regno");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("RegDate");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Mother_name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Father_name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 80, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 80, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 80, 30));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 150, 80, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 150, 80, 30));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 150, 80, 30));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 150, 80, 30));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 150, 90, 30));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 150, 90, 30));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 90, 30));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // findUsers();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
findUsers();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTable_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsersMouseClicked
 int i=jTable_Users.getSelectedRow();
        jTextField1.setText(model.getValueAt(i, 0).toString());
        jTextField2.setText(model.getValueAt(i, 1).toString());
        jTextField3.setText(model.getValueAt(i, 2).toString());
        jTextField4.setText(model.getValueAt(i, 3).toString());        
        jTextField5.setText(model.getValueAt(i, 4).toString());
        jTextField6.setText(model.getValueAt(i, 5).toString());      
        jTextField7.setText(model.getValueAt(i, 6).toString());
        jTextField8.setText(model.getValueAt(i, 7).toString());
        jTextField9.setText(model.getValueAt(i, 8).toString());
        jTextField10.setText(model.getValueAt(i, 9).toString());
        jTextField11.setText(model.getValueAt(i, 10).toString());
        jTextField12.setText(model.getValueAt(i, 11).toString());
        jTextField13.setText(model.getValueAt(i, 12).toString());

 
// TODO add your handling code here:
    }//GEN-LAST:event_jTable_UsersMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i=jTable_Users.getSelectedRow();
          if(i>=0)
          {
              model.setValueAt(jTextField1.getText(), i, 0);
              model.setValueAt(jTextField2.getText(), i, 1);
              model.setValueAt(jTextField3.getText(), i, 2);
              model.setValueAt(jTextField4.getText(), i, 3);
              model.setValueAt(jTextField5.getText(), i, 4);
              model.setValueAt(jTextField6.getText(), i, 5);
              model.setValueAt(jTextField7.getText(), i, 6);
              model.setValueAt(jTextField8.getText(), i, 7);
              model.setValueAt(jTextField9.getText(), i, 8);
              model.setValueAt(jTextField10.getText(), i, 9);
              model.setValueAt(jTextField11.getText(), i, 10);
              model.setValueAt(jTextField12.getText(), i, 11);
              model.setValueAt(jTextField13.getText(), i, 12);
            

              
          }
          try
          {
             String query="UPDATE birthtable SET firstname=?,lastname=?,dob=?,timeofbirth=?,placeofbirth=?,city=?,taluka=?,district=?,gender=?,regdate=?,mothername=?,fathername=? WHERE regno=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(query);
             pst.setString(13, jTextField10.getText());
             pst.setString(1, jTextField1.getText());
             pst.setString(2, jTextField2.getText());
             pst.setString(3, jTextField3.getText());
             pst.setString(4, jTextField4.getText());
             pst.setString(5, jTextField5.getText());
             pst.setString(6, jTextField6.getText());
             pst.setString(7, jTextField7.getText());
             pst.setString(8, jTextField8.getText());
             pst.setString(9, jTextField9.getText());
             pst.setString(10, jTextField11.getText());
             pst.setString(11, jTextField12.getText());
             pst.setString(12, jTextField13.getText());
             

             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"updated succesfully");
          }
          catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"update success");
         }
          jTextField1.setText(" ");
          jTextField2.setText(" ");
          jTextField3.setText(" ");jTextField4.setText(" ");jTextField5.setText(" ");jTextField6.setText(" ");jTextField7.setText(" ");
          jTextField8.setText(" ");
          jTextField9.setText(" ");jTextField10.setText(" ");jTextField11.setText(" ");jTextField12.setText(" ");jTextField13.setText(" ");  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int i=jTable_Users.getSelectedRow();        // TODO add your handling code here:
           if(i>=0)
           {
               model.removeRow(i);
           }
           else
           {
               System.out.print("delete rows");
           }
           try
         {
             String sql="DELETE FROM birthtable WHERE regno=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, jTextField10.getText());
             
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"Remove successfully");
            jTextField1.setText(" ");
          jTextField2.setText(" ");
          jTextField3.setText(" ");jTextField4.setText(" ");jTextField5.setText(" ");jTextField6.setText(" ");jTextField7.setText(" ");
          jTextField8.setText(" ");
          jTextField9.setText(" ");jTextField10.setText(" ");jTextField11.setText(" ");jTextField12.setText(" ");jTextField13.setText(" ");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"Remove success");
         }      // TODO add your handl  // TODO add your handling code here:
                                          
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try
         {
             String sql="INSERT INTO birthtable"+"(firstname,lastname,dob,timeofbirth,placeofbirth,city,taluka,district,gender,regno,regdate,mothername,fathername)"+"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
             con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, jTextField1.getText());
             pst.setString(2, jTextField2.getText());
             pst.setString(3, jTextField3.getText());
             pst.setString(4, jTextField4.getText());
             pst.setString(5, jTextField5.getText());
             
             pst.setString(6, jTextField6.getText());
               
                pst.setString(7, jTextField7.getText());
               
               pst.setString(8, jTextField8.getText());
               pst.setString(9,jTextField9.getText());
               pst.setString(10, jTextField10.getText());
               pst.setString(11, jTextField11.getText());
               pst.setString(12, jTextField12.getText());
               pst.setString(13, jTextField13.getText());
              
             
            
           
                              
             pst.executeUpdate();
             
           JOptionPane.showMessageDialog(null,"inserted successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"inserted success");
         } 
model.insertRow(model.getRowCount(),new Object[]{jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText(),jTextField9.getText(),jTextField10.getText(),jTextField11.getText(),jTextField12.getText(),jTextField13.getText()});
jTextField1.setText(" ");
          jTextField2.setText(" ");
          jTextField3.setText(" ");jTextField4.setText(" ");jTextField5.setText(" ");jTextField6.setText(" ");jTextField7.setText(" ");
          jTextField8.setText(" ");
          jTextField9.setText(" ");jTextField10.setText(" ");jTextField11.setText(" ");jTextField12.setText(" ");jTextField13.setText(" ");
             
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jText_search;
    // End of variables declaration//GEN-END:variables
}
