
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class Birth extends javax.swing.JInternalFrame {

    /**
     * Creates new form Birth
     */
    
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String rd;
    SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
  
    public Birth() {
        initComponents();
        Dob.setDateFormatString("yyyy-MM-dd");
        Regdate.setDateFormatString("yyyy-MM-dd");
        //jPanel1.setVisible(false);
        /*if(jRadioButton1.isSelected())
        {
            rd="Male";
        }
        if(jRadioButton2.isSelected())
                {
                    rd="Female";
                 
                }
        if(jRadioButton3.isSelected())
        {
            rd="Others";
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        POB = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        RN = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        TOB = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        f_name = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        POB1 = new javax.swing.JLabel();
        TOB1 = new javax.swing.JLabel();
        RN1 = new javax.swing.JLabel();
        RD1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Dob = new com.toedter.calendar.JDateChooser();
        Regdate = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 651));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BIRTH CERTIFICATE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FIRST NAME:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("LAST NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("DATE OF BIRTH:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("TIME OF BIRTH:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("PLACE OF BIRTH:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("VILLAGE/CITY:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("TALUKA:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("DISTRICT:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("GENDER:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("REGISTRATION  No:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("REGISTRATION DATE:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("MOTHERS NAME:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("FATHERS NAME:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, -1));

        POB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POBActionPerformed(evt);
            }
        });
        getContentPane().add(POB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niphad", "Nashik", "Dindori", "Satana" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Other");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        RN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RNActionPerformed(evt);
            }
        });
        getContentPane().add(RN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 210, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 220, -1));

        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });
        getContentPane().add(Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 220, 30));

        TOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOBActionPerformed(evt);
            }
        });
        getContentPane().add(TOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 210, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nashik", " " }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 220, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 220, 20));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, -1));
        getContentPane().add(f_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 20));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 210, 20));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 20));
        getContentPane().add(POB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 230, 20));
        getContentPane().add(TOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 200, 20));
        getContentPane().add(RN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 344, 210, 20));
        getContentPane().add(RD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 210, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karsul", "pimpalgaon", "lonewadi", "chehadi" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 220, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));
        getContentPane().add(Dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, 20));
        getContentPane().add(Regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 230, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Generate form");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void POBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POBActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
      rd="Other";  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void TOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOBActionPerformed

    private void RNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RNActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
      rd="Female";  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(f_name.getText().trim().isEmpty() & lname.getText().trim().isEmpty() & TOB1.getText().trim().isEmpty() & POB1.getText().trim().isEmpty()& RN1.getText().trim().isEmpty()) 

    {
         try
         {
             String sql="INSERT INTO birthtable"+"(firstname,lastname,dob,timeofbirth,placeofbirth,city,taluka,district,gender,regno,regdate,mothername,fathername)"+"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";
             con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, firstname.getText());
             pst.setString(2, Lastname.getText());
             //SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
             String s1=smt.format(Dob.getDate());
             pst.setString(3, s1);
             pst.setString(4, TOB.getText());
             pst.setString(5, POB.getText());
             String s3=jComboBox2.getSelectedItem().toString();
             pst.setString(6, s3);
               String s=jComboBox1.getSelectedItem().toString();
                pst.setString(7, s);
                String s2=jComboBox3.getSelectedItem().toString();
                pst.setString(8, s2);
               pst.setString(9,rd);
               pst.setString(10, RN.getText());
                
                String s4=smt.format(Regdate.getDate());
               pst.setString(11, s4);

               pst.setString(12, jTextField5.getText());
               pst.setString(13, jTextField9.getText());
              
             
            
           
                              
             pst.executeUpdate();
             
           JOptionPane.showMessageDialog(null,"inserted successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"inserted success");
         }
            }  
             else
    {
       JOptionPane.showMessageDialog(null,"plz fill all the fields");
    } // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
     
       rd="Male";// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13;
 f1=firstname.getText();
 f2=Lastname.getText();
 f3=smt.format(Dob.getDate());
  f4=TOB.getText();
  f5=POB.getText();
 f6=jComboBox2.getSelectedItem().toString();
 f7=jComboBox1.getSelectedItem().toString();
 f8=jComboBox3.getSelectedItem().toString();
 f9=rd;
 f10=RN.getText();
 f11=smt.format(Regdate.getDate());
 f12=jTextField5.getText();
 f13=jTextField9.getText();
        new BirthPrint(f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13).setVisible(true);
// TODO add your handling code here:
 //new BirthPrint().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(firstname.getText().trim().isEmpty())
        {
            f_name.setText("**please enter this field\"");
        }//    // TODO add your handling code here:
        if(Lastname.getText().trim().isEmpty())
        {
            lname.setText("**please enter this field\"");
        }//
        /* if(DOB.getText().trim().isEmpty())
        {
            dob.setText("**please enter this field\"");
        }//    */
        if(TOB.getText().trim().isEmpty())
        {
            TOB1.setText("**please enter this field\"");
        }//
        if(POB.getText().trim().isEmpty())
        {
            POB1.setText("**please enter this field\"");
        }//
        /*  if(RD.getText().trim().isEmpty())
        {
            RD1.setText("**please enter this field\"");
        }// */
        if(RN.getText().trim().isEmpty())
        {
            RN1.setText("**please enter this field\"");
        }//

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Dob;
    private javax.swing.JTextField Lastname;
    private javax.swing.JTextField POB;
    private javax.swing.JLabel POB1;
    private javax.swing.JLabel RD1;
    private javax.swing.JTextField RN;
    private javax.swing.JLabel RN1;
    private com.toedter.calendar.JDateChooser Regdate;
    private javax.swing.JTextField TOB;
    private javax.swing.JLabel TOB1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel f_name;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lname;
    // End of variables declaration//GEN-END:variables
}
