
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
**/
public class Death1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Death
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Death1() {
        initComponents();
        
        DD.setDateFormatString("yyyy-MM-dd");
        RD.setDateFormatString("yyyy-MM-dd");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PD = new javax.swing.JTextField();
        PA = new javax.swing.JTextField();
        RN = new javax.swing.JTextField();
        NM = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Name1 = new javax.swing.JLabel();
        DD1 = new javax.swing.JLabel();
        PD1 = new javax.swing.JLabel();
        PA1 = new javax.swing.JLabel();
        RN1 = new javax.swing.JLabel();
        RD1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        DD = new com.toedter.calendar.JDateChooser();
        RD = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 651));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Death Certificate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Full Name of Deceased:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 64, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Date of Death:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 248, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Place of Death:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 191, -1, -1));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 64, 357, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Full Name of Mother:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 445, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 373, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Name of Father/Husband:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 506, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Permanent  Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 267, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Registration No:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 328, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Registration Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 396, -1, -1));
        getContentPane().add(PD, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 191, 357, 31));
        getContentPane().add(PA, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 258, 357, 31));

        RN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RNActionPerformed(evt);
            }
        });
        getContentPane().add(RN, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 320, 357, 30));
        getContentPane().add(NM, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 444, 357, 28));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 504, 357, 31));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 563, -1, -1));
        getContentPane().add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 97, 357, 19));
        getContentPane().add(DD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 159, 357, 21));
        getContentPane().add(PD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 228, 357, 24));
        getContentPane().add(PA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 295, 357, 19));
        getContentPane().add(RN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 355, 357, 23));
        getContentPane().add(RD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 424, 357, 14));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 478, 357, 15));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 546, 296, 24));
        getContentPane().add(DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 122, 357, 31));
        getContentPane().add(RD, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 389, 357, 29));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Generate Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 563, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void RNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RNActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               if(Name.getText().trim().isEmpty())
                {
                Name1.setText("**please enter this field\"");
                }//  
            // if(DD.getDate().trim().isEmpty())
//{
    // DD1.setText("**please enter this field\"");
//}//                   //// T        // TODO add your handling code here:
//// T        // TODO add your handling code here:

 if(PD.getText().trim().isEmpty())
{
     PD1.setText("**please enter this field\"");
}//     
  if(PA.getText().trim().isEmpty())
{
     PA1.setText("**please enter this field\"");
}//              
   if(RN.getText().trim().isEmpty())
{
     RN1.setText("**please enter this field\"");
}//                   
   /* if(RD.getText().trim().isEmpty())
{
     RD1.setText("**please enter this field\"");
}// */   
    
     if(NM.getText().trim().isEmpty())
     {
     jLabel18.setText("**please enter this field\"");
     }//     
     if(jTextField8.getText().trim().isEmpty())
     {
     jLabel19.setText("**please enter this field\"");
     }
     if(PD1.getText().trim().isEmpty() & RN1.getText().trim().isEmpty() & jLabel18.getText().trim().isEmpty() & jLabel19.getText().trim().isEmpty()& Name1.getText().trim().isEmpty()& PA1.getText().trim().isEmpty()) 
//
     {
         try
         {
             String sql="INSERT INTO deathtable"+"(name,dob,placeofdeath,permanantadd,regno,regdate,mothername,fathername)"+"VALUES(?,?,?,?,?,?,?,?)";
             con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, Name.getText());
           SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
           String s1=smt.format(DD.getDate());
            pst.setString(2, s1);
             pst.setString(3, PD.getText());
             pst.setString(4, PA.getText());
             pst.setString(5, RN.getText());
             //SimpleDateFormat smt1 =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
           String s2=smt.format(RD.getDate());

             pst.setString(6, s2);
             pst.setString(7, NM.getText());
             pst.setString(8, jTextField8.getText());
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"inserted successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"inserted success");
         }
          
         
        // JOptionPane.showMessageDialog(null,"Database entered");
     }
     else
     {
       JOptionPane.showMessageDialog(null,"plz fill all the fields");
     }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String name,date,place,moname,faname,regdate,regno,padd;
       name=Name.getText();
       SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
          date=smt.format(DD.getDate());
          place=PD.getText();
          place=PA.getText();
          moname=NM.getText();
          faname=jTextField8.getText();
          regno=RN.getText();
          padd=PA.getText();
         regdate=smt.format(RD.getDate());
         new DeathPrint(name,date,place,moname,faname,padd,regno,regdate).setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DD;
    private javax.swing.JLabel DD1;
    private javax.swing.JTextField NM;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JTextField PA;
    private javax.swing.JLabel PA1;
    private javax.swing.JTextField PD;
    private javax.swing.JLabel PD1;
    private com.toedter.calendar.JDateChooser RD;
    private javax.swing.JLabel RD1;
    private javax.swing.JTextField RN;
    private javax.swing.JLabel RN1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
