
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class DeathSearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeathSearch
     */  DefaultTableModel model;
       Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public DeathSearch() {
        initComponents();
         model=(DefaultTableModel) jTable_Users.getModel();
        findUsers();
    }
    public Connection getConnection()
    {
        //Connection con = null;
        
        try{
            con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return con;
    }
    
 // function to return users arraylist with particular data 
    public ArrayList<DeathClass> ListUsers(String ValToSearch)
    {
        ArrayList<DeathClass> usersList = new ArrayList<DeathClass>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `deathtable` WHERE CONCAT(name,dob,placeofdeath,permanantadd,regno,regdate,mothername,fathername) LIKE '%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            DeathClass deathclass;
            //BirthClass b;
            
            while(rs.next())
            {
               deathclass = new DeathClass(
                                 
                                 rs.getString("name"),
                                 rs.getDate("dob"),
                                 rs.getString("placeofdeath"),
                                 rs.getString("permanantadd"),
                                 rs.getInt("regno"),
                                 rs.getDate("regdate"),
                                 rs.getString("mothername"),
                                 rs.getString("fathername")
               
                                );
               usersList.add(deathclass);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    
    // function to display data in jtable
    public void findUsers()
    {
        ArrayList<DeathClass> users = ListUsers(jText_search.getText());
        
        model.setColumnIdentifiers(new Object[]{"Fullname","Dateofdeath","PlaceofDeath","PermanantAdd","Regno","RegDate","MotherName","FatherName"});
        Object[] row = new Object[8];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getFullname();
            row[1] = users.get(i).getDateofdeath();
            row[2] = users.get(i).getPlaceofDeath();
            row[3] = users.get(i).getPermanantAdd();
            row[4] = users.get(i).getRegno();
            row[5] = users.get(i).getRegDate();
            row[6] = users.get(i).getMotherName();
            row[7] = users.get(i).getFatherName();
            
        model.addRow(row);
            
        }
       jTable_Users.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();
        jText_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        dod = new javax.swing.JTextField();
        pod = new javax.swing.JTextField();
        pa = new javax.swing.JTextField();
        regno = new javax.swing.JTextField();
        regdate = new javax.swing.JTextField();
        moname = new javax.swing.JTextField();
        faname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FullName", "Deathofdeath", "PlaceofDeath", "PermanantAdd", "Regno", "RegDate", "MotherName", "FatherName"
            }
        ));
        jTable_Users.setRowHeight(22);
        jTable_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Users);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 267, 888, 90));
        getContentPane().add(jText_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 32, 206, 28));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 31, -1, 28));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 205, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 205, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 205, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("FullName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 122, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("DateOfDeath");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("PlaceOfDeath");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 122, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("PermanantAdd");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 122, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Regno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 122, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("RegDate");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 122, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("MotherName");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 122, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("FatherName");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 122, -1, -1));

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 150, 110, 28));
        getContentPane().add(dod, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 150, 98, 28));
        getContentPane().add(pod, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 150, 94, 28));
        getContentPane().add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 150, 113, 28));

        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        getContentPane().add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 150, 101, 28));
        getContentPane().add(regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 150, 98, 28));

        moname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monameActionPerformed(evt);
            }
        });
        getContentPane().add(moname, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 150, 104, 28));
        getContentPane().add(faname, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 150, 128, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      findUsers();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i=jTable_Users.getSelectedRow();
          if(i>=0)
          {
              model.setValueAt(fullname.getText(), i, 0);
              model.setValueAt(dod.getText(), i, 1);
              model.setValueAt(pod.getText(), i, 2);
              model.setValueAt(pa.getText(), i, 3);
              model.setValueAt(regno.getText(), i, 4);
              model.setValueAt(regdate.getText(), i, 5);
              model.setValueAt(moname.getText(), i, 6);
              model.setValueAt(faname.getText(), i, 7);
            

              
          }
          try
          {
             String query="UPDATE deathtable SET name=?,dob=?,placeofdeath=?,permanantadd=?,regdate=?,mothername=?,fathername=? WHERE regno=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(query);
             pst.setString(8, regno.getText());
             pst.setString(1, fullname.getText());
             pst.setString(2, dod.getText());
             pst.setString(3, pod.getText());
             pst.setString(4, pa.getText());
             pst.setString(5, regdate.getText());
             pst.setString(6, moname.getText());

             pst.setString(7, faname.getText());


             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"updated succesfully");
          }
          catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"update success");
         }
          fullname.setText(" ");
          dod.setText(" ");
          pod.setText(" ");pa.setText(" ");regdate.setText(" ");moname.setText(" ");faname.setText(" ");regno.setText(" ");
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   int i=jTable_Users.getSelectedRow();        // TODO add your handling code here:
           if(i>=0)
           {
               model.removeRow(i);
           }
           else
           {
               System.out.print("delete rows");
           }
           try
         {
             String sql="DELETE FROM deathtable WHERE regno=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, regno.getText());
             
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"Remove successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"Remove success");
         }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try
{
    String sql="INSERT INTO deathtable"+"(name,dob,placeofdeath,permanantadd,regno,regdate,mothername,fathername)"+"VALUES(?,?,?,?,?,?,?,?)";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, fullname.getText());
             pst.setString(2, dod.getText());
             pst.setString(3, pod.getText()); 
             pst.setString(4, pa.getText()); 
             pst.setString(5, regno.getText());
             pst.setString(6, regdate.getText());
             pst.setString(7, moname.getText()); 
             pst.setString(8, faname.getText()); 
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"inserted successfully");
}catch(HeadlessException | SQLException ex)
{
     JOptionPane.showMessageDialog(null,"Insert  success");
}
model.insertRow(model.getRowCount(),new Object[]{fullname.getText(),dod.getText(),pod.getText(),pa.getText(),regno.getText(),regdate.getText(),moname.getText(),faname.getText()}); //  Object[] row=new Object[7];
       fullname.setText(" ");
          dod.setText(" ");
          pod.setText(" ");pa.setText(" ");regno.setText(" ");regdate.setText(" ");moname.setText(" ");faname.setText(" ");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void monameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monameActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void jTable_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsersMouseClicked
   int i=jTable_Users.getSelectedRow();
        fullname.setText(model.getValueAt(i, 0).toString());
        dod.setText(model.getValueAt(i, 1).toString());
        pod.setText(model.getValueAt(i, 2).toString());
        pa.setText(model.getValueAt(i, 3).toString());        
        regno.setText(model.getValueAt(i, 4).toString());
        regdate.setText(model.getValueAt(i, 5).toString());      
         moname.setText(model.getValueAt(i, 6).toString());
 faname.setText(model.getValueAt(i, 7).toString());// TODO add your handling code here:
    }//GEN-LAST:event_jTable_UsersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dod;
    private javax.swing.JTextField faname;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jText_search;
    private javax.swing.JTextField moname;
    private javax.swing.JTextField pa;
    private javax.swing.JTextField pod;
    private javax.swing.JTextField regdate;
    private javax.swing.JTextField regno;
    // End of variables declaration//GEN-END:variables
}
