
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class LivingSearch1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form LivingSearch1
     */
    DefaultTableModel model;
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public LivingSearch1() {
        initComponents();
          model=(DefaultTableModel) jTable_Users.getModel();
          findUsers();
    }
public Connection getConnection()
    {
        //Connection con = null;
        
        try{
            con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return con;
    }
    
 // function to return users arraylist with particular data 
    public ArrayList<LivingClass> ListUsers(String ValToSearch)
    {
        ArrayList<LivingClass> usersList = new ArrayList<LivingClass>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `livingtable` WHERE CONCAT(fullname,address,regdate,regno,taluka)LIKE'%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            LivingClass ls;
            
            while(rs.next())
            {
                ls = new LivingClass(
                                 rs.getString("fullname"),
                                 rs.getString("address"),
                                 rs.getDate("regdate"),
                                 rs.getInt("regno"),
                                 rs.getString("taluka")
                                );
                usersList.add(ls);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    
    // function to display data in jtable
    public void findUsers()
    {
       //jTable_Users.removeAll();
        ArrayList<LivingClass> users = ListUsers(jText_Search.getText());
        
        model.setColumnIdentifiers(new Object[]{"FullName","Address","RegDate","RegNo","Taluka"});
        Object[] row = new Object[5];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getFullName();
            row[1] = users.get(i).getAddress();
            row[2] = users.get(i).getRegDate();
            row[3] = users.get(i).getRegNo();
            row[4] = users.get(i).getTaluka();
            model.addRow(row);
        }
       
       jTable_Users.setModel(model);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();
        UPDATE = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        regdate = new javax.swing.JTextField();
        regno = new javax.swing.JTextField();
        taluka = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jText_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_SearchActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 210, 28));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, 28));

        jTable_Users.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FullName", "Address", "RegDate", "RegNo", "Taluka"
            }
        ));
        jTable_Users.setRowHeight(22);
        jTable_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Users);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 650, 90));

        UPDATE.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UPDATE.setText("DELETE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("ADD");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 80, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Fullname");
        jLabel2.setMaximumSize(new java.awt.Dimension(45, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(45, 14));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("RegDate");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("RegNo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Taluka");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, 20));

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 130, 30));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 120, 30));
        getContentPane().add(regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 130, 30));

        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });
        getContentPane().add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 130, 30));
        getContentPane().add(taluka, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        findUsers(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jText_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_SearchActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnoActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        int i=jTable_Users.getSelectedRow();        // TODO add your handling code here:
           if(i>=0)
           {
               model.removeRow(i);
           }
           else
           {
               System.out.print("delete rows");
           }
           try
         {
             String sql="DELETE FROM livingtable WHERE regno=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, regno.getText());
             
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"Remove successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"Remove success");
         }
          fullname.setText(" ");
          address.setText(" ");
          regdate.setText(" ");regno.setText(" ");taluka.setText(" "); // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     int i=jTable_Users.getSelectedRow();
          if(i>=0)
          {
              model.setValueAt(fullname.getText(), i, 0);
              model.setValueAt(address.getText(), i, 1);
              model.setValueAt(regdate.getText(), i, 2);
              model.setValueAt(regno.getText(), i, 3);
              model.setValueAt(taluka.getText(), i, 4);
            

              
          }
          try
          {
             String query="UPDATE livingtable SET fullname=?,address=?,regdate=?,taluka=? WHERE regno=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(query);
             pst.setString(5, regno.getText());
             pst.setString(1, fullname.getText());
             pst.setString(2, address.getText());
             pst.setString(3, regdate.getText());
             pst.setString(4, taluka.getText());
             
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"updated succesfully");
          }
          catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"update success");
         }
          fullname.setText(" ");
          address.setText(" ");
          regdate.setText(" ");taluka.setText(" ");regno.setText(" ");
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsersMouseClicked
       int i=jTable_Users.getSelectedRow();
        fullname.setText(model.getValueAt(i, 0).toString());
        address.setText(model.getValueAt(i, 1).toString());
        regdate.setText(model.getValueAt(i, 2).toString());
        regno.setText(model.getValueAt(i, 3).toString());        
        taluka.setText(model.getValueAt(i, 4).toString());
       // TODO add your handling code here:
    }//GEN-LAST:event_jTable_UsersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField address;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jText_Search;
    private javax.swing.JTextField regdate;
    private javax.swing.JTextField regno;
    private javax.swing.JTextField taluka;
    // End of variables declaration//GEN-END:variables
}
