
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;


        
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




/**
 *
 * @author lenevo
 */
public class Living_c extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame5
     */
     Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public Living_c() {
        initComponents();
        RD.setDateFormatString("yyyy-MM-dd");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        ADD = new javax.swing.JTextField();
        RN = new javax.swing.JTextField();
        TA = new javax.swing.JTextField();
        FN1 = new javax.swing.JLabel();
        ADD1 = new javax.swing.JLabel();
        RD1 = new javax.swing.JLabel();
        RN1 = new javax.swing.JLabel();
        TA1 = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        RD = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 651));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Full Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 157, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Registration No.:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 302, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Registration Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Taluka");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 377, -1, -1));

        FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNActionPerformed(evt);
            }
        });
        getContentPane().add(FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 87, 340, 33));

        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        getContentPane().add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 154, 340, 32));
        getContentPane().add(RN, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 297, 340, 35));
        getContentPane().add(TA, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 376, 340, 29));
        getContentPane().add(FN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 126, 340, 22));
        getContentPane().add(ADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 192, 340, 22));
        getContentPane().add(RD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 257, 340, 25));
        getContentPane().add(RN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 343, 340, 28));
        getContentPane().add(TA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 411, 279, 23));

        SAVE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("LIVING CERTIFICATE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 29, -1, -1));
        getContentPane().add(RD, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 220, 340, 31));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Generate Form");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
       
         if(FN.getText().trim().isEmpty())
{
     FN1.setText("**please enter this field\"");
} if(ADD.getText().trim().isEmpty())
{
     ADD1.setText("**please enter this field\"");
} /*if(RD.getText().trim().isEmpty())
{
     RD1.setText("**please enter this field\"");
}
*/if(RN.getText().trim().isEmpty())
{
     RN1.setText("**please enter this field\"");
} if(TA.getText().trim().isEmpty())
{
     TA1.setText("**please enter this field\"");
}
  if(FN1.getText().trim().isEmpty() & ADD1.getText().trim().isEmpty() & RN1.getText().trim().isEmpty() & TA1.getText().trim().isEmpty()) 
//
     {
         try
         {
             String sql="INSERT INTO livingtable"+"(fullname,address,regdate,regno,taluka)"+"VALUES(?,?,?,?,?)";
             con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, FN.getText());
             pst.setString(2, ADD.getText());
             SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
             String s1=smt.format(RD.getDate());
             pst.setString(3, s1);
             pst.setString(4, RN.getText());
             pst.setString(5, TA.getText());
             pst.executeUpdate();
             
          //   JOptionPane.ShowMessageDialog(null,"inserted successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"inserted success");
         }
          
         
        // JOptionPane.showMessageDialog(null,"Database entered");
     }
     else
     {
       JOptionPane.showMessageDialog(null,"plz fill all the fields");
     }//  //  //  //  // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADD;
    private javax.swing.JLabel ADD1;
    private javax.swing.JTextField FN;
    private javax.swing.JLabel FN1;
    private com.toedter.calendar.JDateChooser RD;
    private javax.swing.JLabel RD1;
    private javax.swing.JTextField RN;
    private javax.swing.JLabel RN1;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField TA;
    private javax.swing.JLabel TA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
