
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class Marrage extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Marrage() {
        initComponents();
        Marriagedate.setDateFormatString("yyyy-MM-dd");
        Regdate.setDateFormatString("yyyy-MM-dd");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        Wname = new javax.swing.JTextField();
        Pm = new javax.swing.JTextField();
        rn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Wname1 = new javax.swing.JLabel();
        Pm1 = new javax.swing.JLabel();
        Md1 = new javax.swing.JLabel();
        rn1 = new javax.swing.JLabel();
        rd1 = new javax.swing.JLabel();
        Marriagedate = new com.toedter.calendar.JDateChooser();
        Regdate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 651));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Marriage Certificate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name of Husband:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Name of Wife:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Place of Marriage:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 218, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Marriage Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 278, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Registration No.:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 341, -1, -1));

        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 81, 426, 33));

        Wname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WnameActionPerformed(evt);
            }
        });
        getContentPane().add(Wname, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 148, 430, 30));

        Pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PmActionPerformed(evt);
            }
        });
        getContentPane().add(Pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 216, 431, 31));
        getContentPane().add(rn, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 340, 429, 29));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 464, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Regisatration Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 398, -1, -1));
        getContentPane().add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 120, 426, 21));
        getContentPane().add(Wname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 184, 430, 19));
        getContentPane().add(Pm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 253, 431, 19));
        getContentPane().add(Md1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 314, 431, 15));
        getContentPane().add(rn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 375, 429, 17));
        getContentPane().add(rd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 437, 422, 16));
        getContentPane().add(Marriagedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 278, 431, 30));
        getContentPane().add(Regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 398, 427, 28));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Generate Form");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 463, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PmActionPerformed

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void WnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(NAME.getText().trim().isEmpty())
{
     Name1.setText("**please enter this field\"");
}//    //// TODO add your handling code here:
          if(Wname.getText().trim().isEmpty())
{
     Wname1.setText("**please enter this field\"");
}
     
           if(Pm.getText().trim().isEmpty())
{
     Pm1.setText("**please enter this field\"");
}
/* if(Md.getText().trim().isEmpty())
{
     Md1.setText("**please enter this field\"");
}*/
 if(rn.getText().trim().isEmpty())
{
     rn1.setText("**please enter this field\"");
}
/* if(rd.getText().trim().isEmpty())
{
     rd1.setText("**please enter this field\"");
}*/
  if(Name1.getText().trim().isEmpty() & Wname1.getText().trim().isEmpty() & Pm1.getText().trim().isEmpty() & rn1.getText().trim().isEmpty()) 
//
     {
         try
         {
             String sql="INSERT INTO marriagetable"+"(husbandname,wifename,placeofmarriage,marriagedate,regdate,regno)"+"VALUES(?,?,?,?,?,?)";
             con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, NAME.getText());
             pst.setString(2, Wname.getText());
             pst.setString(3, Pm.getText());
             SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
             String s1=smt.format(Marriagedate.getDate());
             pst.setString(4, s1);
             String s2=smt.format(Regdate.getDate());
             pst.setString(5, s2);
             pst.setString(6, rn.getText());
             pst.executeUpdate();
             
          //   JOptionPane.ShowMessageDialog(null,"inserted successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"inserted success");
         }
          
         
        // JOptionPane.showMessageDialog(null,"Database entered");
     }
     else
     {
       JOptionPane.showMessageDialog(null,"plz fill all the fields");
     }
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Marriagedate;
    private javax.swing.JLabel Md1;
    private javax.swing.JTextField NAME;
    private javax.swing.JLabel Name1;
    private javax.swing.JTextField Pm;
    private javax.swing.JLabel Pm1;
    private com.toedter.calendar.JDateChooser Regdate;
    private javax.swing.JTextField Wname;
    private javax.swing.JLabel Wname1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel rd1;
    private javax.swing.JTextField rn;
    private javax.swing.JLabel rn1;
    // End of variables declaration//GEN-END:variables
}
