
package gpms;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenevo
 */
public class Table extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Table() {
        initComponents();
        model=(DefaultTableModel) jTable_Users.getModel();
       findUsers();
        
        
       
    }
    public Connection getConnection()
    {
              
        
        try{
            con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return con;
    }
    
 // function to return users arraylist with particular data 
    public ArrayList<Table1> ListUsers(String ValToSearch)
    {
        ArrayList<Table1> usersList = new ArrayList<Table1>();
        
        Statement st;
        ResultSet rs;
        
        try{
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `schemetable` WHERE CONCAT(no,description,purchasedate,noofthings,cost,completiondate,remainingamount)LIKE'%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            Table1 ls;
            
            while(rs.next())
            {
                ls = new Table1(
                                 rs.getInt("no"),
                                 rs.getString("description"),
                                 rs.getInt("purchasedate"),
                                 rs.getInt("noofthings"),
                                 rs.getInt("cost"),
                                 rs.getInt("completiondate"),
                                 rs.getInt("remainingamount")
                        
                                );
                usersList.add(ls);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    
    // function to display data in jtable
    public void findUsers()
    {
        ArrayList<Table1> users = ListUsers(jText_Search.getText());
      
        model.setColumnIdentifiers(new Object[]{"No","Description","Purchase_Date","No_of_Things","Cost","Completion_Date","Remaining_amount"});
        Object[] row = new Object[7];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getNo();
            row[1] = users.get(i).getDescription();
            row[2] = users.get(i).getPurchase_Date();
            row[3] = users.get(i).getNo_of_Things();
            row[4] = users.get(i).getCost();
            row[5] = users.get(i).getCompletion_Date();
            row[6] = users.get(i).getRemaining_amount();

            
            
            model.addRow(row);
        }
       jTable_Users.setModel(model);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        noTF = new javax.swing.JTextField();
        pdTF = new javax.swing.JTextField();
        notTF = new javax.swing.JTextField();
        coTF = new javax.swing.JTextField();
        comTF = new javax.swing.JTextField();
        raTF = new javax.swing.JTextField();
        desTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jText_Search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1150, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Description", "Purchase_Date", "No_of_Things", "Cost", "Completion_Date", "Remaining_amount"
            }
        ));
        jTable_Users.setRowHeight(20);
        jTable_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Users);
        if (jTable_Users.getColumnModel().getColumnCount() > 0) {
            jTable_Users.getColumnModel().getColumn(6).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 301, 869, 129));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 235, 73, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 134, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Purchase Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 134, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("No.of Things");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 134, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Cost");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 134, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Completion Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 134, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Remaining amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(906, 134, -1, -1));

        noTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTFActionPerformed(evt);
            }
        });
        getContentPane().add(noTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 178, 75, 30));

        pdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdTFActionPerformed(evt);
            }
        });
        getContentPane().add(pdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 178, 118, 30));

        notTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notTFActionPerformed(evt);
            }
        });
        getContentPane().add(notTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 178, 115, 30));

        coTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coTFActionPerformed(evt);
            }
        });
        getContentPane().add(coTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 178, 112, 30));

        comTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTFActionPerformed(evt);
            }
        });
        getContentPane().add(comTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 178, 108, 30));

        raTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raTFActionPerformed(evt);
            }
        });
        getContentPane().add(raTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 178, 114, 30));
        getContentPane().add(desTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 178, 199, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("REMOVE");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 235, 73, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 235, 73, -1));
        getContentPane().add(jText_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 28, 235, 29));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 29, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 28, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
         try
         {
             String sql="INSERT INTO schemetable"+"(no,description,purchasedate,noofthings,cost,completiondate,remainingamount)"+"VALUES(?,?,?,?,?,?,?)";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, noTF.getText());
             pst.setString(2, desTF.getText());
             pst.setString(3, pdTF.getText());
             pst.setString(4, notTF.getText());
             pst.setString(5, coTF.getText());
             pst.setString(6, comTF.getText());
             pst.setString(7, raTF.getText());
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"inserted successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"inserted success");
         }
          
        model.insertRow(model.getRowCount(),new Object[]{noTF.getText(),desTF.getText(),pdTF.getText(),notTF.getText(),coTF.getText(),comTF.getText(),raTF.getText()}); //  Object[] row=new Object[7];
       noTF.setText(" ");
          desTF.setText(" ");
          pdTF.setText(" ");notTF.setText(" ");coTF.setText(" ");comTF.setText(" ");raTF.setText(" ");
         /*  String sql="INSERT INTO schemestable"+"(husbandname,wifename,placeofmarriage,marriagedate,regdate,regno)"+"VALUES(?,?,?,?,?,?)";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, NAME.getText());
             pst.setString(2, Wname.getText());
             pst.setString(3, Pm.getText());
             SimpleDateFormat smt =new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
             String s1=smt.format(Marriagedate.getDate());
             pst.setString(4, s1);
             String s2=smt.format(Regdate.getDate());
             pst.setString(5, s2);
             pst.setString(6, rn.getText());
             pst.executeUpdate();
          */
        //jTable1./*();*/   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdTFActionPerformed

    private void coTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coTFActionPerformed

    private void raTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raTFActionPerformed

    private void noTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTFActionPerformed

    private void comTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comTFActionPerformed

    private void notTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notTFActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_notTFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int i=jTable_Users.getSelectedRow();        // TODO add your handling code here:
           if(i>=0)
           {
               model.removeRow(i);
           }
           else
           {
               System.out.print("delete rows");
           }
           try
         {
             String sql="DELETE FROM schemetable WHERE no=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(sql);
             pst.setString(1, noTF.getText());
             
             pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null,"Remove successfully");
             
         }
         catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"Remove success");
         }
           noTF.setText(" ");
          desTF.setText(" ");
          pdTF.setText(" ");notTF.setText(" ");coTF.setText(" ");comTF.setText(" ");raTF.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed
      
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int i=jTable_Users.getSelectedRow();
          if(i>=0)
          {
              model.setValueAt(noTF.getText(), i, 0);
              model.setValueAt(desTF.getText(), i, 1);
              model.setValueAt(pdTF.getText(), i, 2);
              model.setValueAt(notTF.getText(), i, 3);
              model.setValueAt(coTF.getText(), i, 4);
              model.setValueAt(comTF.getText(), i, 5);
              model.setValueAt(raTF.getText(), i, 6);

              
          }
          try
          {
             String query="UPDATE schemetable SET description=?,purchasedate=?,noofthings=?,cost=?,completiondate=?,remainingamount=? WHERE no=?";
             con=(Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/forms","root","");
             pst=(PreparedStatement) con.prepareStatement(query);
             pst.setString(7, noTF.getText());
             pst.setString(1, desTF.getText());
             pst.setString(2, pdTF.getText());
             pst.setString(3, notTF.getText());
             pst.setString(4, coTF.getText());
             pst.setString(5, comTF.getText());
             pst.setString(6, raTF.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"updated succesfully");
          }
          catch(HeadlessException | SQLException ex)
         {
             JOptionPane.showMessageDialog(null,"update success");
         }
          noTF.setText(" ");
          desTF.setText(" ");
          pdTF.setText(" ");notTF.setText(" ");coTF.setText(" ");comTF.setText(" ");raTF.setText(" ");
          
          
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsersMouseClicked
        int i=jTable_Users.getSelectedRow();
        noTF.setText(model.getValueAt(i, 0).toString());
        desTF.setText(model.getValueAt(i, 1).toString());
        pdTF.setText(model.getValueAt(i, 2).toString());
        notTF.setText(model.getValueAt(i, 3).toString());        
        coTF.setText(model.getValueAt(i, 4).toString());
        comTF.setText(model.getValueAt(i, 5).toString()); 
        raTF.setText(model.getValueAt(i, 6).toString());        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_UsersMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   findUsers();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coTF;
    private javax.swing.JTextField comTF;
    private javax.swing.JTextField desTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jText_Search;
    private javax.swing.JTextField noTF;
    private javax.swing.JTextField notTF;
    private javax.swing.JTextField pdTF;
    private javax.swing.JTextField raTF;
    // End of variables declaration//GEN-END:variables
}
